# The west manifest file (west.yml) for MCUXpresso SDK overall delivery.
#
# The per-workspace west configuration file, ${workspace_path}/.west/config,
# specifies the path of the project containing this manifest file, the
# path is relative to the workspace location ${workspace_path}.
#
#     [manifest]
#     path = core
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
  remotes:
  - name: nxpmicro
    url-base: https://github.com/NXPmicro
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxpmicro
  self:
    path: core
  projects:
  - name: mcux-sdk-examples
    revision: 39eed09d6a8485dcf365a24cd6ef957e7cc6fbf8
    path: examples
    remote: nxp-mcuxpresso
  - name: mcux-sdk-middleware-connectivity-framework
    revision: a45ed24bc5f8d54312c4d9243c4423d226084412
    path: middleware/wireless/framework
    remote: nxp
  - name: mcux-sdk-middleware-bluetooth-controller
    path: middleware/wireless/ble_controller
    revision: 0e4effc707a0d5569160b9335bc2e57c17255f01
    remote: nxp
  - name: mcux-sdk-middleware-bluetooth-host
    path: middleware/wireless/bluetooth
    revision: e5a1b7b9e3b44b49c6c0318edfc3acac74b342d8
    remote: nxp
  - name: mcux-sdk-middleware-ieee_802.15.4
    path: middleware/wireless/ieee-802.15.4
    revision: 7cca871d58e53c78a703a39b269c4366b03f26e4
    remote: nxp
  - name: mcux-sdk-middleware-zigbee
    path: middleware/wireless/zigbee
    revision: ef9636fafec2c76fa12d7ebe910b9925733b8ed0
    remote: nxp-mcuxpresso
  - name: amazon-freertos
    path: rtos/amazon-freertos
    revision: fb74168634e716fb5f0a61714e5c0d1ac6246bac
    remote: nxp
  - name: mbedtls
    path: middleware/mbedtls
    revision: 15458495823165de372f62c3dad621a8da6c86e3
    remote: nxp-mcuxpresso