# The west manifest file (west.yml) for MCUXpresso SDK overall delivery.
#
# The per-workspace west configuration file, ${workspace_path}/.west/config,
# specifies the path of the project containing this manifest file, the
# path is relative to the workspace location ${workspace_path}.
#
#     [manifest]
#     path = core
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
  remotes:
  - name: nxpmicro
    url-base: https://github.com/NXPmicro
  - name: nxp
    url-base: https://github.com/NXP
  defaults:
    remote: nxpmicro
  self:
    path: core
  projects:
  - name: mcux-sdk-examples
    revision: MCUX_2.6.8_K32W0
    path: examples
  - name: mcux-sdk-middleware-connectivity-framework
    revision: bbbaaae606d648d09dec114ba5af3576157c4a00
    path: middleware/wireless/framework
    remote: nxp
  - name: mcux-sdk-middleware-bluetooth-controller
    path: middleware/wireless/ble_controller
    revision: 3110cbd5fcf990d5abcdb854faae0fcf47fdcdeb
    remote: nxp
  - name: mcux-sdk-middleware-bluetooth-host
    path: middleware/wireless/bluetooth
    revision: ec98bfbe7cc532a276510fbf19ee28655a511cba
    remote: nxp
  - name: mcux-sdk-middleware-ieee_802.15.4
    path: middleware/wireless/ieee-802.15.4
    revision: ad4f547473376245f94cbfa45cbdaf5ca6f7def0
    remote: nxp
  - name: amazon-freertos
    path: rtos/amazon-freertos
    revision: ffb8ee5a7e0490df3ea235432a1af7740f74e3f0
  - name: mbedtls
    path: middleware/mbedtls
    revision: 15458495823165de372f62c3dad621a8da6c86e3
