# The west manifest file (west.yml) for MCUXpresso SDK overall delivery.
#
# The per-workspace west configuration file, ${workspace_path}/.west/config,
# specifies the path of the project containing this manifest file, the
# path is relative to the workspace location ${workspace_path}.
#
#     [manifest]
#     path = core
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
  remotes:
    - name: nxpmicro
      url-base: https://github.com/NXPmicro
    - name: nxp
      url-base: https://github.com/NXP
  defaults:
    remote: nxpmicro
  projects:
    - name: mcux-sdk-examples
      revision: MCUX_2.9.4_MW320
      path: examples
    - name: FreeRTOS-Kernel
      revision: MCUX_2.9.4_MW320
      path: rtos/freertos/freertos_kernel
    - name: mcux-sdk-middleware-sdmmc
      revision: 3789034d53336cf6ca73d7777aa05fd7d2d81ad3
      path: middleware/sdmmc
    - name: mcux-sdk-middleware-multicore
      path: middleware/multicore
      revision: db55c7f400910c82a6084d8385e2ba68c860426b
    - name: rpmsg-lite
      path: middleware/multicore/rpmsg_lite
      url:  https://github.com/NXPmicro/rpmsg-lite
      revision: v3.1.1
    - name: erpc
      path: middleware/multicore/erpc
      url:  https://github.com/EmbeddedRPC/erpc
      revision: 1.8.0
    - name: lwip
      path: middleware/lwip
      revision: 4ef9433dee75f3597f782d817a432b0cf950750d
    - name: mbedtls
      path: middleware/mbedtls
      revision: 75010b7b49c72067f4c3e57361975069075bca74
    - name: wifi_nxp
      path: middleware/wifi
      revision: 8fbb64dd7a0384efdd46dd5fe8ea8172b70e7adb
      remote: nxp
  self:
    path: core
